/**
 * Copyright (C) 2019, Xiongfa Li.
 * All right reserved.
 * @author xiongfa.li
 * @version V1.0
 * Description: 
 */

package main

var sqlType2GoMap = map[string]string{
    "int":                "int",
    "integer":            "int",
    "tinyint":            "int",
    "smallint":           "int",
    "mediumint":          "int",
    "bigint":             "int64",
    "int unsigned":       "uint",
    "integer unsigned":   "uint",
    "tinyint unsigned":   "uint",
    "smallint unsigned":  "uint",
    "mediumint unsigned": "uint",
    "bigint unsigned":    "uint64",
    "bit":                "int",
    "bool":               "bool",
    "enum":               "string",
    "set":                "string",
    "varchar":            "string",
    "char":               "string",
    "tinytext":           "string",
    "mediumtext":         "string",
    "text":               "string",
    "longtext":           "string",
    "blob":               "string",
    "tinyblob":           "string",
    "mediumblob":         "string",
    "longblob":           "string",
    "date":               "time.Time",
    "datetime":           "time.Time",
    "timestamp":          "time.Time",
    "time":               "time.Time",
    "float":              "float64",
    "double":             "float64",
    "decimal":            "float64",
    "binary":             "string",
    "varbinary":          "string",
}

var sqlType2IfValueMap = map[string]string{
    "int":                "-1",
    "integer":            "-1",
    "tinyint":            "-1",
    "smallint":           "-1",
    "mediumint":          "-1",
    "bigint":             "-1",
    "int unsigned":       "0",
    "integer unsigned":   "0",
    "tinyint unsigned":   "0",
    "smallint unsigned":  "0",
    "mediumint unsigned": "0",
    "bigint unsigned":    "0",
    "bit":                "-1",
    "bool":               "false",
    "enum":               "nil",
    "set":                "nil",
    "varchar":            "nil",
    "char":               "nil",
    "tinytext":           "nil",
    "mediumtext":         "nil",
    "text":               "nil",
    "longtext":           "nil",
    "blob":               "nil",
    "tinyblob":           "nil",
    "mediumblob":         "nil",
    "longblob":           "nil",
    "date":               "nil",
    "datetime":           "nil",
    "timestamp":          "nil",
    "time":               "nil",
    "float":              "-1",
    "double":             "-1",
    "decimal":            "-1",
    "binary":             "nil",
    "varbinary":          "nil",
}
