/**
 * Copyright (C) 2019, Xiongfa Li.
 * All right reserved.
 * @author xiongfa.li
 * @version V1.0
 * Description: 
 */

package generator

import (
    "fmt"
    "github.com/xfali/gobatis-cmd/pkg/common"
    "github.com/xfali/gobatis-cmd/pkg/config"
    "github.com/xfali/gobatis-cmd/pkg/io"
    "github.com/xfali/gobatis-cmd/pkg/mapping"
    "strings"
    "time"
)

func findTime(model []common.ModelInfo) bool {
    for _, info := range model {
        if info.DataType == "date" || info.DataType == "datetime" || info.DataType == "timestamp" || info.DataType == "time" {
            return true
        }
    }
    return false
}

func GenModel(config config.Config, tableName string, model []common.ModelInfo) {
    modelDir := config.Path
    if !io.IsPathExists(modelDir) {
        io.Mkdir(modelDir)
    }
    fileName := config.ModelFile
    if fileName == "" {
        fileName = strings.ToLower(tableName) + ".go"
    }
    exist := io.IsPathExists(modelDir + fileName)
    modelFile, err := io.OpenAppend(modelDir + fileName)
    if err == nil {
        defer modelFile.Close()

        modelName := common.TableName2ModelName(tableName)
        builder := strings.Builder{}
        if !exist {
            builder.WriteString(fmt.Sprintf("//This file was generated by xfali/gobatis-cmd at"))
            builder.WriteString(common.Newline())
            builder.WriteString("//")
            builder.WriteString(time.Now().String())
            builder.WriteString(common.Newline())
            builder.WriteString(common.Newline())

            builder.WriteString("package ")
            builder.WriteString(config.PackageName)
            builder.WriteString(common.Newline())
            builder.WriteString(common.Newline())

            builder.WriteString("import (")
            builder.WriteString(common.Newline())
            builder.WriteString(common.ColumnSpace())
            builder.WriteString(`"github.com/xfali/gobatis"`)
            builder.WriteString(common.Newline())
            if findTime(model) {
                builder.WriteString(common.ColumnSpace())
                builder.WriteString(`"time"`)
                builder.WriteString(common.Newline())
            }
            builder.WriteString(")")
            builder.WriteString(common.Newline())
            builder.WriteString(common.Newline())
        }

        builder.WriteString("type ")
        builder.WriteString(modelName)
        builder.WriteString(" struct {")
        builder.WriteString(common.Newline())

        builder.WriteString(common.ColumnSpace())
        builder.WriteString(fmt.Sprintf("//TableName gobatis.ModelName `%s`", tableName))
        builder.WriteString(common.Newline())

        for _, info := range model {
            builder.WriteString(common.ColumnSpace())
            builder.WriteString(common.Column2Modelfield(info.ColumnName))
            builder.WriteString(" ")
            builder.WriteString(mapping.SqlType2GoMap[info.DataType])
            builder.WriteString(" ")
            //builder.WriteString(fmt.Sprintf("`%s:\"%s\"`", config.TagName, info.ColumnName))
            writeTag(&builder, config.TagName, info.ColumnName)
            builder.WriteString(common.Newline())
        }
        builder.WriteString("}")
        builder.WriteString(common.Newline())
        builder.WriteString(common.Newline())

        //select
        builder.WriteString(fmt.Sprintf("func (m *%s) Select(sess *gobatis.Session) ([]%s, error) {", modelName, modelName))
        builder.WriteString(common.Newline())
        builder.WriteString(common.ColumnSpace())
        builder.WriteString(fmt.Sprintf("return Select%s(sess, *m)", modelName))
        builder.WriteString(common.Newline())
        builder.WriteString("}")
        builder.WriteString(common.Newline())
        builder.WriteString(common.Newline())

        //count
        builder.WriteString(fmt.Sprintf("func (m *%s) Count(sess *gobatis.Session) (int64, error) {", modelName))
        builder.WriteString(common.Newline())
        builder.WriteString(common.ColumnSpace())
        builder.WriteString(fmt.Sprintf("return Select%sCount(sess, *m)", modelName))
        builder.WriteString(common.Newline())
        builder.WriteString("}")
        builder.WriteString(common.Newline())
        builder.WriteString(common.Newline())

        //insert
        builder.WriteString(fmt.Sprintf("func (m *%s) Insert(sess *gobatis.Session) (int64, int64, error) {", modelName))
        builder.WriteString(common.Newline())
        builder.WriteString(common.ColumnSpace())
        builder.WriteString(fmt.Sprintf("return Insert%s(sess, *m)", modelName))
        builder.WriteString(common.Newline())
        builder.WriteString("}")
        builder.WriteString(common.Newline())
        builder.WriteString(common.Newline())

        //update
        builder.WriteString(fmt.Sprintf("func (m *%s) Update(sess *gobatis.Session) (int64, error) {", modelName))
        builder.WriteString(common.Newline())
        builder.WriteString(common.ColumnSpace())
        builder.WriteString(fmt.Sprintf("return Update%s(sess, *m)", modelName))
        builder.WriteString(common.Newline())
        builder.WriteString("}")
        builder.WriteString(common.Newline())
        builder.WriteString(common.Newline())

        //delete
        builder.WriteString(fmt.Sprintf("func (m *%s) Delete(sess *gobatis.Session) (int64, error) {", modelName))
        builder.WriteString(common.Newline())
        builder.WriteString(common.ColumnSpace())
        builder.WriteString(fmt.Sprintf("return Delete%s(sess, *m)", modelName))
        builder.WriteString(common.Newline())
        builder.WriteString("}")
        builder.WriteString(common.Newline())
        builder.WriteString(common.Newline())

        io.Write(modelFile, []byte(builder.String()))
    }
}

const(
    defaultTag = "xfield"
)

func writeTag(b *strings.Builder, tagName, columnName string) string {
    oriTags := strings.Split(tagName, ",")
    var tags []string
    found := false
    for _, v := range oriTags {
        if v != "" {
            if v == defaultTag {
                found = true
            }
            tags = append(tags, v)
        }
    }

    if !found {
        tags = append(tags, defaultTag)
    }

    l := len(tags)
    b.WriteString("`")
    for _, tag := range tags {
        if tag == "" {
            continue
        }
        b.WriteString(fmt.Sprintf("%s:\"%s\"", tag, columnName))
        l--
        if l > 0 {
            b.WriteString(" ")
        }
    }
    b.WriteString("`")
    return b.String()
}
